" Some initial methods we need. "
Reak on: Object as: 'rubyPerform:'                expose: 'send'.
Reak on: Object as: 'rubyPerform:with:'           expose: 'send'.
Reak on: Object as: 'rubyPerform:with:with:'      expose: 'send'.
Reak on: Object as: 'rubyPerform:with:with:with:' expose: 'send'.
Reak on: Module as: 'defineMethod:'               expose: 'define_smalltalk_method'.
Reak on: Class  as: 'new'                         expose: 'new'.
Reak on: Class  as: 'new:'                        expose: 'new'.

